name: oelkemusic
favicon: null
layout_spectrum: 0.73018
typography_spectrum: 0.63555
title: Brigitte Oelke - Singer/ Actress/ Producer
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-35197250-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070a05'
    - '#fafafa'
    - '#bfbcb0'
    - '#818272'
    - '#732106'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
