name: oelkemusic
favicon: null
layout_spectrum: 1
typography_spectrum: 0.14962
title: Brigitte Oelke - Singer/ Actress/ Producer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#b75a2f'
    - '#ceb36c'
    - '#3f1f10'
    - '#bc6e3c'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
