title: Brigitte Oelke - Singer/ Actress/ Producer
cta:
  domain: null
  version: null
  bucket: null
layout_spectrum: 1
favicon: null
name: oelkemusic
purpose: []
analytics:
  facebook: null
  google: UA-35197250-2
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.2957447
  lightness: 0.5
  saturation: 0.4983137
  rhythmicContrast: 0.817032
  brandColors:
    - '#070a05'
    - '#fafafa'
    - '#bfbcb0'
    - '#818272'
    - '#732106'
typography_spectrum: 0.6255319
