title: Brigitte Oelke - Singer/ Actress/ Producer
cta:
  version: null
  bucket: null
  domain: null
layout_spectrum: 1
favicon: null
name: oelkemusic
purpose: []
analytics:
  twitter: null
  google: UA-35197250-2
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.272344
  lightness: 1
  saturation: 0.1875
  rhythmicContrast: 0
  brandColors:
    - '#000000'
    - '#b75a2f'
    - '#ceb36c'
    - '#3f1f10'
    - '#bc6e3c'
typography_spectrum: 1
