name: Brigitte Oelke
favicon: null
layout_spectrum: 0
typography_spectrum: 0.3635795
title: Brigitte Oelke - Singer/ Actress/ Producer
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-35197250-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070a05'
    - '#fafafa'
    - '#bfbcb0'
    - '#818272'
    - '#732106'
  brandStrength: 1
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.08322904
purpose: []
