name: oelkemusic.com
favicon: null
layout_spectrum: 0.68655
typography_spectrum: 0.3635795
title: Brigitte Oelke
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-35197250-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#b75a2f'
    - '#ceb36c'
    - '#3f1f10'
    - '#bc6e3c'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
